curl -X 'POST' 'http://localhost:8080/Flight_recognition' -H 'accept: application/json' -H 'Content-Type: application/json' \
      -d '{
"Flight": {
    "Flight Carrier": "DL",
    "flight time": "09:30",
    "flight date": "2023-09-05",
    "passengers": [
     {
                    "milestone multiple": 0,
                    "priority": 0,
                    "delay": true,
                    "is a 360 member": false,
                    "days since last Delta flight": 201,
                    "IROP severity level": 0,
                    "days since SkyMiles member": 17,
                    "days since new tier": 0,
                    "quarantined": false,
                    "medallion member": true,
                    "corporate flyer": true,
                    "military": false,
                    "age": 35,
                    "group booking size": 2,
                    "employee": false,
                    "unaccompanied minor": false,
                    "infant": false,
                    "skymiles member": true,
                    "seat": 22,
                    "last reveived recognition": "2021-02-17",
                    "million miler": true,
                    "status": "Silver",
                    "missed connection": true,
                    "name": "Bob Jones"
                },
                {
                    "milestone multiple": 1,
                    "priority": 0,
                    "delay": true,
                    "is a 360 member": true,
                    "days since last Delta flight": 0,
                    "IROP severity level": 1,
                    "days since SkyMiles member": 1835,
                    "days since new tier": 177,
                    "quarantined": false,
                    "medallion member": true,
                    "corporate flyer": true,
                    "military": false,
                    "age": 35,
                    "group booking size": 2,
                    "employee": false,
                    "unaccompanied minor": false,
                    "infant": false,
                    "skymiles member": true,
                    "seat": 10,
                    "last reveived recognition": "2022-09-05",
                    "million miler": true,
                    "status": "Gold",
                    "missed connection": true,
                    "name": "Jane Doe"
                },
                {
                    "milestone multiple": 2,
                    "priority": 0,
                    "delay": false,
                    "is a 360 member": false,
                    "days since last Delta flight": 0,
                    "IROP severity level": 0,
                    "days since SkyMiles member": 746,
                    "days since new tier": 0,
                    "quarantined": false,
                    "medallion member": false,
                    "corporate flyer": false,
                    "military": false,
                    "age": 27,
                    "group booking size": 7,
                    "employee": false,
                    "unaccompanied minor": false,
                    "infant": false,
                    "skymiles member": true,
                    "seat": 46,
                    "last reveived recognition": "2022-09-05",
                    "million miler": false,
                    "status": "Silver",
                    "missed connection": false,
                    "name": "Greg Smith"
                }
    ],
    "distance": 580
  }
}'